const PDFDocument = require('pdfkit');
const fs = require('fs');

const generatePDF = (content, filePath) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                margin: 50,
                size: 'A4'
            });
            
            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);
            

            doc.fontSize(20)
               .fillColor('#2563eb')
               .text('🚀 Your Daily MERN Stack Jobs', { align: 'center' });
            
            doc.fontSize(12)
               .fillColor('#6b7280')
               .text(new Date().toLocaleDateString('en-US', { 
                   weekday: 'long', 
                   year: 'numeric', 
                   month: 'long', 
                   day: 'numeric' 
               }), { align: 'center' });
            
            doc.moveDown(2);
            

            doc.fontSize(11)
               .fillColor('#1f2937')
               .text(content, {
                   align: 'left',
                   lineGap: 5
               });
            

            doc.moveDown(3);
            doc.fontSize(10)
               .fillColor('#9ca3af')
               .text('Generated by JobSync - Your Daily Job Alert Service', { align: 'center' });
            
            doc.end();
            
            stream.on('finish', resolve);
            stream.on('error', reject);
            
        } catch (error) {
            reject(error);
        }
    });
};

module.exports = generatePDF;